name: Jupyter Notebook Automation

on:
  schedule:
    - cron: '0 6 * * *'  # 매일 오전 6시 실행 (UTC 기준)
  workflow_dispatch:  # 수동 실행 가능

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: 리포지토리 체크아웃
        uses: actions/checkout@v3

      - name: Python 환경 설정
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 필수 패키지 설치
        run: pip install notebook pandas numpy matplotlib

      - name: Jupyter Notebook 실행
        run: jupyter nbconvert --execute --to notebook --inplace scripts/analysis.ipynb

      - name: 실행된 Notebook 저장 및 푸시
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add scripts/analysis.ipynb
          git commit -m "자동 실행: Jupyter Notebook 업데이트"
          git push
